name: khipu_pay
description: Plugin to create payment identifiers, process payments and verify the
  status of a payment through the Khipu platform.
version: 1.0.0
homepage: https://github.com/DuckyTieDev/khipu_pay

flutter:
  plugin:
    platforms:
      android:
        package: com.duckytie.khipupay
        pluginClass: KhipuPayPlugin
      ios:
        pluginClass: KhipuPayPlugin

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.1
  crypto: ^2.1.4
  cryptoutils: ^0.4.0
  diacritic: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"
